### ISSUE TITLE
timeoutWait function doesn't work with ESP8266

### ISSUE THREAD

**Issue by certeza** [adafruit/Adafruit-Thermal-Printer-Library#23]
The timeoutWait function uses:
`while((long)(micros() - resumeTime) < 0L); // (syntax is rollover-proof)`

This won't work with ESP8266 because it leaves the processor no time to do other things.
For ESP8266 it should be changed to a delay() call.
I use delay(10) and that works fine.

**Comment by bmjbmj** [comment]
Yes I noticed the same when the printer printed: "Soft WDT reset ctx: cont, followed by a stack dump" after running throe a couple of lines from the example program provided. This is because hardware serial on the ESP8266 sends out debug information 'as a last will' ;-) A (barley working) workaround is to use 'yield();' in the example program but any longer transmission (like the picture) still fails.
